name: 'Post PR Comment'
description: 'Posts a comment to a PR with results using github-script'
inputs:
  comment-file:
    description: 'Path to file containing comment content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Post comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('${{ inputs.comment-file }}', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: results
          });

